### ISSUE TITLE
objectionSoftDelete is not a function

### ISSUE THREAD

**Issue by sebalvaro** [alex-w0/objection-js-soft-delete#116]
Node version: 14.x
Objection version: 3.0.0
Knex Version: 0.9.13
SoftDelete version: 3.0.1

objectionSoftDelete throws this error 

```
const softDelete = objectionSoftDelete({
                   ^

TypeError: objectionSoftDelete is not a function
    at file:///mnt/sdc2/.../src/models/ImedModel.js:4:20
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
```

My model: 
```js
import { Model } from 'objection';
import objectionSoftDelete from 'objection-js-soft-delete';

const softDelete = objectionSoftDelete({
  columnName: 'status',
  deletedValue: false,
  notDeletedValue: true,
});

export default class ImedModel extends softDelete(Model) {
  $beforeInsert() {
    this.created_at = new Date().toISOString();
  }

  $beforeUpdate() {
    this.updated_at = new Date().toISOString();
  }
}

```

**Comment by alex-w0** [comment]
There is something wrong with the import, it wraps the module with an additional default property, even if the export function from the module seems to be okay.

```
{ default: [Function: softDelete] }
```

Can you create a reproduction link (codesandbox.io...) to give me a better understanding how you have configured node?

In the meantime you can workaround this issue by simply accessing the property directly:

```
const softDelete = objectionSoftDelete.default({
  columnName: 'status',
  deletedValue: false,
  notDeletedValue: true,
});
```

**Comment by alexcroox** [comment]
Did you ever resolve this with ESM / modern versions of node? I've been using the .default work around for months but now adding jest tests it doesn't like the .default

**Comment by alex-w0** [comment]
@alexcroox  I didn't looked into it because noone has provided a reproduction link and since I do not actively maintain this package (I just took it from someone else), I did not want to spend further time on it. 

If you are interested in solving this problem, please open a pull request or if you need any assist, please provide a reproduction link.
